---
title: "Questions"
output: html_document
---

1.	According to John Tukey, what is more important than having data?
2.	In which type of analysis is it most essential to use randomized experiments to ensure valid results?
3.	What best describes a mechanistic data analysis?
4.	What is the difference between prediction and inference in data science?
5.	What is the main purpose of inferential data analysis?
6.	What type of object is created by default when using c(1, 2, 3)?
7.	What will be the result of c(1, 2, 3) + c(4, 5, 6) in R?
8.	Which control structure is used to exit a loop in R?
9.	Which function adds a title to a base R plot?
10.	Which function applies a function to each element of a list and returns a list?
11.	Which function in base R is commonly used to read comma-separated data files?
12.	Which function in dplyr is used to filter rows based on a condition?
13.	Which function is used to save a plot in ggplot2?
14.	Which of the following is used for assignment in R?
15.	Which operator is used to extract elements of a list by name?	
16.	Which type of data analysis would be best suited for discovering unknown patterns or relationships in data?
17.	Why is “big data” not always better than “small data”?
18.	Correlation implies causation.
19.	Which of the following is the correct order of data analysis question types from simplest to most complex?
20.	What is the main goal of descriptive data analysis?
